# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddEditCoffeeForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(AddEditCoffeeForm)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.nameLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.label_2 = QtWidgets.QLabel(AddEditCoffeeForm)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.roastLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.roastLineEdit.setObjectName("roastLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.roastLineEdit)
        self.label_3 = QtWidgets.QLabel(AddEditCoffeeForm)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.typeLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.typeLineEdit.setObjectName("typeLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.typeLineEdit)
        self.label_4 = QtWidgets.QLabel(AddEditCoffeeForm)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.descriptionLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.descriptionLineEdit.setObjectName("descriptionLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.descriptionLineEdit)
        self.label_5 = QtWidgets.QLabel(AddEditCoffeeForm)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.priceDoubleSpinBox = QtWidgets.QDoubleSpinBox(AddEditCoffeeForm)
        self.priceDoubleSpinBox.setMaximum(99999.0)
        self.priceDoubleSpinBox.setSingleStep(1.0)
        self.priceDoubleSpinBox.setObjectName("priceDoubleSpinBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.priceDoubleSpinBox)
        self.label_6 = QtWidgets.QLabel(AddEditCoffeeForm)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.volumeLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.volumeLineEdit.setObjectName("volumeLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.volumeLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.okButton = QtWidgets.QPushButton(AddEditCoffeeForm)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(AddEditCoffeeForm)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(AddEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Добавить/Редактировать запись"))
        self.label.setText(_translate("AddEditCoffeeForm", "Название сорта"))
        self.label_2.setText(_translate("AddEditCoffeeForm", "Степень обжарки"))
        self.label_3.setText(_translate("AddEditCoffeeForm", "Молотый/в зернах"))
        self.label_4.setText(_translate("AddEditCoffeeForm", "Описание вкуса"))
        self.label_5.setText(_translate("AddEditCoffeeForm", "Цена"))
        self.label_6.setText(_translate("AddEditCoffeeForm", "Объем упаковки"))
        self.okButton.setText(_translate("AddEditCoffeeForm", "OK"))
        self.cancelButton.setText(_translate("AddEditCoffeeForm", "Отмена"))
